hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    user-service:
      path: /users/**
      serviceId: user-service
      stripPrefix: false

    product-service:
      path: /products/**
      serviceId: product-service
      stripPrefix: false

    image-service:
      path: /images/**
      serviceId: image-service
      stripPrefix: false

server:
  port: 8989
