routes:
  user-service:
    path: /users/**
    serviceId: user-service
    stripPrefix: false

  product-service:
    path: /products/**
    serviceId: product-service
    stripPrefix: false

  image-service:
    path: /images/**
    serviceId: image-service
    stripPrefix: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

server:
  port: 9100
