spring:
  jpa:
    database: POSTGRESQL
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: validate
    properties:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/image_service_database
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  packagesToScan: com.alexandersuetnov.imageservice
