spring:
  jpa:
    database: MySQL
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: validate
    properties:
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/user_service_database?useSSL=false&serverTimezone=UTC
    username: bestuser
    password: bestuser
    driver-class-name: org.postgresql.Driver


server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  packagesToScan: com.alexandersuetnov.userservice
