spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
  profiles:
    active: native
  security:
    user:
      password: admin

server:
  port: 8088
